### ISSUE TITLE
Certain Rise Player for ChromeOS Displays only show error messages instead of media.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/chrome-os-player#150]
+*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue*
+
+- Operating System Version: Chrome OS 8530.96.0
+- Player Version: RisePlayer 2018.08.28.8208 Free
+- Viewer Version: 2-01-201808201721
+
+##### What is the expected behavior?
+ Display should show Image and Video Media.
+
+##### What is the actual behavior?
+ Display shows error message "File is downloading" or "Please wait while your image is downloaded" images never download and display.
+
+##### What steps can be taken to replicate the problem? 
+ Have not been able to replicate, but multiple users have reported the issue. It can be seen on the Display screenshot.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) User Blocked: Issue 150 - Certain Rise Player for ChromeOS Displays only show error messages instead of media.](https://trello.com/c/qJZInRcc/8683-3-user-blocked-issue-150-certain-rise-player-for-chromeos-displays-only-show-error-messages-instead-of-media)

**Comment by robb-price** [comment]
Since this can be corrected by upgrading your Chrome version, and setting it so it appears in this doc: https://docs.google.com/document/d/1qsAE_WpaUqtywtZdghNXflj-r5HwWz5ai5JUQrmyu5s/edit#, we can close this issue.

**Comment by andrecardoso** [comment]
@robb-price @btfrise we're also releasing a fix for it. It is in beta now, but it will fix it on old chrome versions when released. Thanks!

**Comment by andrecardoso** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) ChrOS: Add webstreams polyfill](https://trello.com/c/pZShwvdW/4701-2-chros-add-webstreams-polyfill)
