### ISSUE TITLE
ChromeOS Scheduling Issue

### ISSUE THREAD

**Issue by colby-maughan** [Rise-Vision/chrome-os-player#151]
- Operating System Version: Chrome OS 10718.88.2
- Player Version: RisePlayer 2018.08.28.8208 Free
- Viewer Version: 2-01-201808201721

##### What is the expected behavior?
 Rise Player ceases to display a black screen when scheduling tells it to begin playing content.

##### What is the actual behavior?
 Once the player is on a black screen due to scheduling, even if you set the timeline to "Always" the black screen is not lifted. 

##### What steps can be taken to replicate the problem? 
1.  Set a schedule on a ChromeOS device.
2. Wait for the ChromeOS device to change the screen to black.
3. Set the timeline to "Always"
4. Screen should still be black.

**Comment by tejohnso** [comment]
@colby-maughan with the email that has gone out, plus our plan to address scheduling in viewer as part of the html outside of viewer epic, plus our recent fix to improve reboots on chrome os, I think this can be closed.

**Comment by colby-maughan** [comment]
@tejohnso I agree, it looks like you guys have taken care of the issue. Thanks for your efforts here and I apologize for dropping the ball with the initial report - I'll make sure that doesn't happen again.
