### ISSUE TITLE
ChromeOS Players do not obey scheduled reboot.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/chrome-os-player#152]
+*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue*
+
+- Operating System Version: Chrome OS 10718.88.2
+- Player Version: RisePlayer 2018.08.28.8208 Licensed
+- Viewer Version: 2-01-201808201721
--

+
+##### What is the expected behavior?
+Player should reboot after getting scheduled reboot command.
+
+##### What is the actual behavior?
+Does not reboot.
+
+##### What steps can be taken to replicate the problem? 
+
+1. Set up a ChromeOS Display and schedule a reboot.

**Comment by andrecardoso** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) ChrOS: Enable reboot on non-kiosk mode](https://trello.com/c/dr93ozDK/4719-1-chros-enable-reboot-on-non-kiosk-mode)

**Comment by robb-price** [comment]
@andrecardoso Looks like this is corrected with the updated beta!

**Comment by robb-price** [comment]
Issue is corrected and will be rolled out when the new beta goes into production. Closing this issue.
