### ISSUE TITLE
Proxy not working for Rise Player in managed mode

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/chrome-os-player#155]
##### What is the expected behavior?
You should be able to set a proxy for Rise Player on ChromeOS in kiosk mode. You can set proxy settings for users on the ChromeOS device, but not single-app kiosk sessions: https://support.google.com/chrome/a/answer/2657289 

##### What is the actual behavior?
There's no option to set proxy settings for single app kiosk mode applications. Seems to be related to the issue described in this bug report: https://discuss.kiosk.cook.company/t/it-does-not-use-proxy-settings-in-kiosk-mode-on-chromebox/113 

##### What steps can be taken to replicate the problem? 
N/A

##### Additional Info

According to the user, they were originally able to setup proxy settings using the deprecated community version of Rise Player by clicking on the the blue Configure Network Settings text that would appear below the Rise Logo after it fails the network checks.

**Comment by tejohnso** [comment]
@kaden-rise can you review the help center changes as per [trello card](https://trello.com/c/vul272VH) and close?

**Comment by kaden-rise** [comment]
@tejohnso Sent the client a link to the updated guide. Waiting to hear back if it worked.

**Comment by tejohnso** [comment]
Closing, please re-open if necessary.
