### ISSUE TITLE
ChromeOS player not rebooting as set in the Display Settings

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/chrome-os-player#159]
- Operating System Version: Chrome OS 10895.56.0
- Player Version: RisePlayer 2018.08.28.8208 Licensed
- Viewer Version: 2-01-201808201721

##### What is the expected behavior?
ChromeOS Media Players should reboot according to the reboot settings set on the Display Settings page.

##### What is the actual behavior?
Nothing happens when the time set in the reboot settings is reached on the Media Player.

##### What steps can be taken to replicate the problem? 

1.  Set a Reboot timeframe for a ChromeOS display in the Display settings
2. Wait until the timeframe is reached and nothing will happen

**Comment by kaden-rise** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User Blocked: Issue 159 - ChromeOS player not rebooting as set in the Display Settings](https://trello.com/c/mLE2cSMO/8799-user-blocked-issue-159-chromeos-player-not-rebooting-as-set-in-the-display-settings)

**Comment by tejohnso** [comment]
@kaden-rise please re-open if necessary
