### ISSUE TITLE
Rise Player not using RLS

### ISSUE THREAD

**Issue by rudibravo** [Rise-Vision/chrome-os-player#162]
##### What is the expected behavior?

Rise Player use RLS to download images.

##### What is the actual behavior?

Some displays are not using RLS and are downloading the files directly from GCS.

##### What steps can be taken to replicate the problem? 

There are no repro steps.
The displays affected have a timing issue when loading viewer. Viewer executes before Rise Player injection happens.

**Comment by rudibravo** [comment]
We attempt to fix it on this PR unsuccessfully https://github.com/Rise-Vision/chrome-os-player/pull/158

**Comment by tejohnso** [comment]
Fixed with timing correction.
Some displays are still not using RLS but that's a widget issue  https://github.com/Rise-Vision/widget-video/issues/250
