### ISSUE TITLE
Player only retries connection once 

### ISSUE THREAD

**Issue by tylermwight** [Rise-Vision/chrome-os-player#168]
- Operating System Version:Chrome OS 10895.78.0
- Player Version:RisePlayer 2018.10.19.7090 Licensed
- Viewer Version:2-01-201810182053

##### What is the expected behavior?
When Player cannot connect it retries it's connection x times to ensure network is fully connected after startup

##### What is the actual behavior?
 Player retires just once and if it gets an error (ERR_CONNECTION_RESET in this case) and if the retry fails it will show the grey spinner indefinitely 

##### What steps can be taken to replicate the problem? 

1. Reset a connection while Rise Player is trying to connect

**Comment by andrecardoso** [comment]
Released on 2018.11.01.7361 version
