### ISSUE TITLE
ChromeOS Players showing white screen due to communication issues between player and viewer

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/chrome-os-player#171]
- Operating System Version: Chrome OS 11021.56.0
- Player Version: RisePlayer 2018.10.19.7090
- Viewer Version: 2-01-201810182053

##### What is the expected behavior?
Rise Player should run without going to a white screen

##### What is the actual behavior?
Rise Player fails to show any content and gets stuck on a white screen

##### What steps can be taken to replicate the problem? 

1. N/A

##### Update
There are reports that this is only happening on Chrome version 70.

**Comment by kaden-rise** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User Blocked: Issue #171 - ChromeOS Players showing white screen due to communication issues between player and viewe](https://trello.com/c/Q21ecN6x/8895-user-blocked-issue-171-chromeos-players-showing-white-screen-due-to-communication-issues-between-player-and-viewe)

**Comment by andrecardoso** [comment]
Fixed on release 2018.11.06.7840
