### ISSUE TITLE
ChromeOS player different behavior than Windows Player

### ISSUE THREAD

**Issue by tylermwight** [Rise-Vision/chrome-os-player#172]
- Operating System Version: Chrome OS 10895.56.0
- Player Version: RisePlayer 2018.10.19.7090 Licensed
- Viewer Version:	2-01-201810182053

##### What is the expected behavior?
 ChromeOS player should behave as the Windows Player. If the issue is with the presentation, both players should show same behavior

##### What is the actual behavior?
For certain presentations CHromeOS and Windows players behave differently. In this specific case the presentation will go black on the chromeOS player after 15 minutes, but the Windows one has been playing without issues for days. This was done on multiple chromeos players. After the chromeOS player goes black, the screenshot function throws errors

##### What steps can be taken to replicate the problem? 
Check out the displays that are having these issues. The error is happening right you. It can be replicated by rebooting the device and running this presentation for about 15min-1hr (info in the card)

**Comment by PatrickA-RiseVision** [comment]
Chrome OS update resolved.
