### ISSUE TITLE
Videos stop playing and a black screen appears after a while

### ISSUE THREAD

**Issue by andrecardoso** [Rise-Vision/chrome-os-player#174]
- Operating System Version: Chrome 70
- Player Version: RisePlayer 2018.11.01.7361 Licensed
- Viewer Version: Chrome OS 11021.56.0

##### What is the expected behavior?
Videos keep playing

##### What is the actual behavior?
A black screen appears

##### What steps can be taken to replicate the problem? 
1. Set up a presentation with a video widget configure to a folder with 16 webm videos
1. Wait until the black screen appears

**Comment by stulees** [comment]
Tested folder of 17 videos on several Chromebit devices. Only encountered a black screen for one device but this was due to its time based schedule (8am - 6pm). Can't reproduce black screen otherwise, closing.
