### ISSUE TITLE
Buttons aren't highlighted when you tab through them

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/chrome-os-player#180]
*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue*

##### What is the expected behavior?
When you're setting up player for the first time or re-entering the Display ID it would be easier to do it with only a keyboard if the buttons became highlighted as you tabbed through them. 

##### What is the actual behavior?
The buttons don't appear active when you're on them.

##### What steps can be taken to replicate the problem? 
Try setting up player with only a keyboard.

**Comment by andrecardoso** [comment]
Fix released in version 2018.11.26.7756
