### ISSUE TITLE
Multiple videos causes the player to crash to the dead pixel face.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/chrome-os-player#182]
+*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue*
+
+- Operating System Version: Chrome OS 10895.56.0 and Chrome OS 10718.88.2
+- Player Version: (Beta) RisePlayer 2018.11.26.7541 and RisePlayer 2018.11.06.7840
+- Viewer Version: 2-01-201811191457 
+
+##### What is the expected behavior?
The same amount of videos that can play on Windows and Linux Player should be able to play on ChromeOS Player.

+##### What is the actual behavior?
When playing on the ChromeOS Player, the attached Presentation crashes to a dead pixel face after a non specific period of time. Sometimes it takes 20 minutes, sometimes 2 hours, but it always happens. This does not happen on Windows or Linux.

+##### What steps can be taken to replicate the problem? 
1. Play this Presentation on a ChromeOS Player: https://apps.risevision.com/editor/workspace/e1a37ad9-69a0-4885-9813-eebc80efbac0/?cid=556323b8-984c-4127-aa08-4d73d019bcb8

**Comment by tejohnso** [comment]
https://trello.com/c/aEktXdDA/4860-2-chros-monitor-uptime-renderer-failure-and-restart-renderer-on-multiple-failures-validate-uptime-99
