### ISSUE TITLE
Presentation with video widget pointed to a folder of video files freezes on ChromeOS display

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/chrome-os-player#184]
Operating System | Chrome OS 11021.81.0
Player Version | RisePlayer 2018.12.04.6715 Free
Viewer Version | 2-01-201811191457
Browser Version | Chrome 70.0.3538.110

**Expected Behavior:**
Presentations pointed to videos should play indefinitely

**Actual Behavior:**
Presentation with video widget pointed to a folder of video files in Rise Storage eventually freezes. 

**Steps to reproduce:**

1. Create a Presentation with a video widget pointed to a folder of 30+ webm videos.
2. Schedule that Presentation to a ChromeOS Display
3. Wait for the freezing to occur

**Comment by stulees** [comment]
Fixed with update to Video Widget in https://github.com/Rise-Vision/widget-video/pull/258
