### ISSUE TITLE
Videos with Audio won't autoplay in Chrome OS when "No user gesture is required" is not set.

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/chrome-os-player#199]
- Operating System Version:	Chrome OS 11316.148.0
- Player Version: RisePlayer 2019.02.07.9756 Free
- Viewer Version: 2-01-201902262134

##### What is the expected behavior?
Videos play automatically in Rise Player when the Video Widget is used, even when there is audio.  The autoplay setting is controlled by Rise Player.

##### What is the actual behavior?
Videos will only autoplay in Rise Player when the Video Widget is used if there is no audio, or if "No user gesture is required" is enabled.

##### What steps can be taken to replicate the problem? 

1. Add a presentation including a video with sound to your Chrome Player's schedule.
1. In the local settings on your Chrome Player, disable the autoplay setting "No user gesture is required" 
1. The video will no longer auto play until you disable the setting.

**Comment by btfrise** [comment]
Closing pending clarification from customer.
