### ISSUE TITLE
HTML Presentations don't work offline

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/chrome-os-player#227]
Operating System Version: Chrome OS 11895.95.0
Player Version: (Beta) RisePlayer 2019.07.02.8458 Licensed -but also happened with stable version

##### What is the expected behavior?
When I disconnect my internet (by powering off my router), HTML Presentations should continue to play

##### What is the actual behavior?
A "No Internet" screen from Chrome appears and HTML Presentations are not shown. 

##### What steps can be taken to replicate the problem? 
1. Create a Schedule with two HTML Presentations and run on your CrOS Display
1. Disconnect the Internet
1. You will see a gray "No Internet" screen.

**Comment by andrecardoso** [comment]
This was fixed by https://github.com/Rise-Vision/chrome-os-player/pull/228
