### ISSUE TITLE
Video Template on Chrome OS - video playback is choppy, crashes player

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/chrome-os-player#233]
- Operating System Version: Chrome OS 11021.81.0
- Player Version: RisePlayer 2019.09.04.9951 Licensed

##### What is the expected behavior?
Video Template works passably on Chrome player; video playback runs smoothly and does not crash.

##### What is the actual behavior?
Over time, Video Template stops working on Chrome player.  Over time, the blue background starts showing up before and after the video.  Playback becomes choppy and eventually Player crashes.

##### What steps can be taken to replicate the problem? 

1. Create a presentation from Video Template that runs an mp4 video.
2. Schedule it to play on a Chromebit or Chromebox running Rise Player.
3. Let it run for some time and observe the behavior.

**Comment by santiagonoguez** [comment]
@PatrickA-RiseVision I assume this is blocking a user, right ? And also, you are implying any MP4 video will eventually cause this behavior, or which size of video were you testing ? Thanks !

**Comment by PatrickA-RiseVision** [comment]
@santiagonoguez to confirm, this is blocking a user on 3 Chromebit Displays.
I'm testing with videos on the customer playlist, and I also tried the default video that plays when you add the Video Template.  I'll share links on the card.

**Comment by PatrickA-RiseVision** [comment]
@santiagonoguez one of the users who reported this confirmed that the Video Template on its own doesn't crash the player.  It only crashes if he adds other templates to the schedule.

I'm wondering if it could be related to the PUD issue rather than the Video Template, since the default for Video Template is to PUD.  I'm going to try testing the same schedule on my display without PUD this afternoon.

**Comment by santiagonoguez** [comment]
@PatrickA-RiseVision thanks, I'm taking this one next !

**Comment by santiagonoguez** [comment]
Most affected displays recovered by changing their videos to WEBM. It could be the format under ChromeOS, but the much lower file size may also have helped.

We've been waiting for response on other users, but as that has not arrived, we'll be closing this for the time being.

@PatrickA-RiseVision @stulees
