### ISSUE TITLE
Display never updates to show the Player Version, instead shows blank Display Settings, with "Player Version Not Current"

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/chrome-os-player#234]
+*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue*
+
+- Operating System Version: ChromeOS 59.0.3071.91
+- Player Version: 2019.09.04.9951
+- Viewer Version: N/A
+
+##### What is the expected behavior?
The Display should show the correct information for the Player running on it.

+##### What is the actual behavior?
The Display Settings are entirely blank, and the Display shows as Not Activated

+##### What steps can be taken to replicate the problem? 
Not sure, this is the only device we have see this with.

**Comment by tejohnso** [comment]
@robb-price closing as discussed

https://trello.com/c/kqKRNb8V/5535-3-defect-234-display-never-updates-to-show-the-player-version-instead-shows-blank-display-settings-with-player-version-not-curre
