### ISSUE TITLE
Deleted images when a folder is played in Image Widget

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/chrome-os-player#239]
- Operating System Version: Chrome OS 12239.92.2
- Player Version: RisePlayer 2019.11.13.1006 Licensed
- Viewer Version: 2-01-201911181548

##### What is the expected behavior?
Image widget plays all images in a folder when a folder is selected.  When an image is added, it is played in the widget.  When an image is removed, it is no longer played.

##### What is the actual behavior?
Under some conditions, Chrome Players play content that has been removed from the folder.  Changes to the folder appear to be ignored.

##### What steps can be taken to replicate the problem? 
We have this currently happening on a specific Display.  I will share the details privately.

On my Display, I was able to cause similar behavior by disconnecting my Chromebit from the Internet and deleting files from the folder.

1. Create a folder in storage.
2. Add a number of images to the folder.
3. Play the folder in an Image Widget.
4. Let the content cache on a Chrome Player.
5. Disconnect the Chrome Player from the Internet.
6. Delete images in the folder.
7. Reconnect the Chrome Player to the Internet.

After deleting multiple files, they continued to play on the Display even though it had been reconnected and rebooted.  After making another change, however, the content updated and was correct.

I haven't been able to cause the state the affected player is in.

**Comment by andrecardoso** [comment]
@PatrickA-RiseVision isn't this the same as https://github.com/Rise-Vision/rise-launcher-electron/issues/829 ?

**Comment by PatrickA-RiseVision** [comment]
@andrecardoso possibly?  I didn't think so from description of the behavior:

Rise-Vision/rise-launcher-electron#829 is an html template that won't update on a user Display.

In #239 above, an image widget isn't receiving updates when a folder is changed.

It's possible the cause is the same (disconnected from messaging service); I'll defer to your expertise.

**Comment by andrecardoso** [comment]
@PatrickA-RiseVision yep, the side effects are different but the cause is the same: displays not getting updates from MS. I've manually fixed the other displays on the server side and might be able to do it here as well. Could you please send me the list of display ids?

**Comment by PatrickA-RiseVision** [comment]
@andrecardoso I'll add it to the main list for LMS issues so it's documented.  I'm closing this since it's therefore a duplicate.
