### ISSUE TITLE
Google Slides is blank/white when shown through HTML Widget on Chrome OS

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/chrome-os-player#250]
- Operating System Version: Chrome 69, 70, 77
- Player Version: RisePlayer 2020.02.05.8680 
- Viewer Version: 2-01-202002281716

##### What is the expected behavior?

- Google Slides embedded in the HTML Widget plays correctly on the Display.

##### What is the actual behavior?

- Google Slides embedded in the HTML Widget goes white on the Display.

##### What steps can be taken to replicate the problem? 

1. Embed a Google Slideshow in the HTML Widget 
1. Add the Presentation to a Schedule  
1. See a white screen

Video: https://www.screencast.com/t/hvbSnkfEy

Note: From my testing this does not seem to happen on Electron player, only Chrome OS

**Comment by sheadarlison** [comment]
@Rise-Vision/tyler @PatrickA-RiseVision I'm going to leave this defect with you, if Dev has questions can you please help them out. 

Thanks

**Comment by andrecardoso** [comment]
@sheadarlison @PatrickA-RiseVision I believe this is just another instance of https://github.com/Rise-Vision/rise-vision-apps/issues/1561 which should have been fixed now. Could you please confirm?

**Comment by sheadarlison** [comment]
@andrecardoso no, it's not, I had the problem happen with only one HTML Widget in a schedule.

**Comment by andrecardoso** [comment]
@sheadarlison did you test it again? I couldn't reproduce this issue after we deployed the fix for 1561.

**Comment by sheadarlison** [comment]
@andrecardoso when did that fix get deployed?

**Comment by andrecardoso** [comment]
@sheadarlison Yesterday around 3:20 PM EST

**Comment by sheadarlison** [comment]
@andrecardoso thanks, I haven't been able to reproduce today. 

I'd like Patrick to try reproducing and if he can't I'm good to close the issue.

He should be able to try in an hour. 

Thanks

**Comment by sheadarlison** [comment]
Confirmed this is now working correctly.
