### ISSUE TITLE
Video Presentations eventually go black on the ChromeOS Player

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/chrome-os-player#251]
+*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue*
+
+- Operating System Version: Chrome OS 11021.81.0
+- Player Version: RisePlayer 2020.02.05.8680 Licensed
+- Viewer Version: 2-01-202006301322
+
+##### What is the expected behavior?
Similar to the Windows and Linux Player, the videos should continue without issue as set in the Schedule.

+##### What is the actual behavior?
 The screens will go black and show nothing after roughly 15 - 30 minutes. The only way to get it back is save the Schedule, Presentation, or restart the Display.

+##### What steps can be taken to replicate the problem? 

Create a Presentation from the Full Screen Video Presentation Template, and play that on a ChromeOS Display. Eventually, it will turn black. A Schedule of Presentations is necessary if needed.

**Comment by stulees** [comment]
Issue fixed with https://github.com/Rise-Vision/common-template/pull/139 , cc: @olegrise
