### ISSUE TITLE
Rise Player does not start on Chrome 84

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/chrome-os-player#254]
+*NOTE: do not add Display ID, Company ID or ScreenConnect links to this comment. Instead, manually add these details to the Trello Card. The card will be added to the [Delivery Sprint Backlog](https://trello.com/b/eDYWD5Gs/delivery) after you've submitted the issue*
+
+- Operating System Version: 84.0.4147.136
+- Player Version: N/A
+- Viewer Version: N/A
+
##### What is the expected behavior?
The Player should start as expected after being installed on Chrome OS 84.0.4147.136

##### What is the actual behavior?
The Player can be installed, add in the Display ID, and then it sits on the loading animation. It never starts the Player, and after 5 minutes, goes from Online to Not Activated in the Display Settings. None of the Display Settings information ever loads.

##### What steps can be taken to replicate the problem? 

1. On a machine running Chrome OS 84.0.4147.136, install the Player. 

Currently we have only run into this with users who are running non enrolled Players, but we want to correct this before we set the enrolled Player to go to this Chrome OS version.

**Comment by tejohnso** [comment]
This is an issue with Chrome 84 and Chrome 85 that will be fixed in Chrome 86, which is scheduled for release to stable on October 15th.  In the meantime we should update our article to discourage updating.

**Comment by tejohnso** [comment]
I've confirmed that this does not affect apps running in kiosk mode

**Comment by alanclayton** [comment]
@tejohnso given we don't support player in non-kiosk mode I think this can be closed. Thanks
