### ISSUE TITLE
Photo Feed Widget can't find images from Google Photos only on Chrome OS and in preview

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/chrome-os-player#255]
- Operating System Version: Chrome OS 11021.81.0
- Player Version: RisePlayer  2020.02.05.8680
- Viewer Version:  2-01-202006181648

##### What is the expected behavior?
Photofeed widget has consistent behavior on Electron player, Chrome OS player, and in preview.

##### What is the actual behavior?
Photofeed widget can play images from Google Photos as expected on Electron versions of Rise Player.
Photofeed widget can see folders in Editor, but when Previewed the folder appears to always be empty.  An error is returned in the console:
`Access to XMLHttpRequest at 'https://account.testinseconds.com/ImageGalleryWidgetService/Service.svc/GetPictureData?companyId=42921d20-4828-45dd-9ba9-6badb5778fbc&displayId=&widgetId=sc0_pre0_ph0_0w&encryptedUserId=null&encryptedAccessToken=pghU37/Xkl1mFK3bafh5NPS0P7wS3JSgnix8+MujfVgI6ZTUgxmIVcWgWwQOp2BHiKNeDmv97t/M+k1GCbTX7ckaCaPTZpC8vP/zmjJscdEpI/fkL3qosPrACbFqMdQ9J7yHalMNbAXeKeU79zUsOOa1j2aFkTbcYEvKpFNxFSrrzhbk/J6jTl4O2LFEn1eHh3TADjkCuJ5Sngd/x2AIHI4VzAQ2op1zHIi7J28HNfUmFhHzqlHi0g==&encryptedRefreshToken=BdJoVE/jlDIX3GVB6Nfo4F7jq88xwpIJ0hP5RGBMBAo1jtRKUswslN9MgJI9cCZ8ePet+Hjx4sIYJeOGK0oFdetvy9luUZhjVxDZjholqkhVL4Rplusx23Fvz0jhLs+EZjiiVJvfEvA=&photoSharingSite=Google&imageCount=5&imageIds=&hashtag=&album=AIenwm1PBNnaZBXlkDAuCCCKdubiXRgImlL6WrPqo-7cJobWEJIHxYUbFECyFhjD8fXtmvQb-sJd&includeSubfolders=false&retrieveOrder=date&isRandom=false&userName=patrick.arsenault@risevision.com&maxHeight=783px&maxWidth=1269px&forceRefreshPhotos=true' from origin 'https://widgets.risevision.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
On Chrome OS, the folder always appears to be empty.

This leads to 2 displays side by side behaving differently while playing the same presentation; a linux player playing a folder of images, and a chrome os player showing an error that no photos are available.

##### What steps can be taken to replicate the problem? 
1. Create a new presentation from a blank template
2. Add the Photo Feed widget
3. Connect the widget to Google Photos
4. Choose a folder to play images from
5. Save and publish the presentation
6. Add the presentation to a schedule that plays on a Chrome OS player

**Comment by stulees** [comment]
This has been fixed with https://github.com/Rise-Vision/viewer/pull/474 and https://github.com/Rise-Vision/rise-vision-apps/pull/2274
